# Generated by Django 5.2.4 on 2025-08-06 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BookName', models.CharField(max_length=50)),
                ('Title', models.CharField(choices=[('c1', 'Derama'), ('c2', 'Action'), ('c3', 'SienceFiction'), ('c4', 'Sience'), ('c5', 'Story')], max_length=40)),
                ('Author', models.CharField(max_length=40)),
                ('TimeCreated', models.DateTimeField(auto_now=True)),
                ('Creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
