# Generated by Django 5.2.4 on 2025-08-08 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Title',
            field=models.CharField(choices=[('Derama', 'Derama'), ("Action'", 'Action'), ('SienceFiction', 'SienceFiction'), ('Sience', 'Sience'), ('Story', 'Story')], max_length=40),
        ),
    ]
